In [ ]:
# Task 1: Matrix Implementation
# a. Create the matrix
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Original Matrix:")
for row in matrix:
    print(row)

In [ ]:
# b. Transform the matrix (Transpose)
transposed_matrix = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
print("\nTransposed Matrix:")
for row in transposed_matrix:
    print(row)

In [ ]:
# Task 2: Tuples Implementation
# a. Creating a tuple
tuple1 = (1, 2, 3, 4, 5)
print("\nTuple1:", tuple1)


In [ ]:

# b. Create two tuples and merge together
tuple2 = ('a', 'b', 'c')
merged_tuple = tuple1 + tuple2
print("Merged Tuple:", merged_tuple)


In [ ]:
# c. Print the elements in tuple
print("Elements in tuple:", merged_tuple)

In [ ]:
# Task 3: Array Implementation
# a. Defining an array
array = [10, 20, 30, 40, 50]
# b. Print the array
print("\nArray:", array)
# c. Print the last element
print("Last element of the array:", array[-1])

In [ ]:
# Task 4: Date functions
# a. Today's date
print("\nToday's Date:", datetime.date.today())
# b. Birthday (Example)
birthday = datetime.date(2000, 5, 15)
print("Example Birthday:", birthday)

In [1]:
# Task 5: Numpy Implementation
# a. Import numpy as np (already done)
import numpy as np
import datetime

# b. Concatenation of two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("\nConcatenated Array:", concatenated_arr)


Concatenated Array: [1 2 3 4 5 6]


In [ ]:
# c. Create an empty array
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)


In [2]:
# d. Create an array of consecutive integers
consecutive_arr=np.arange(10)
print("Array of consecutive Integer: ",consecutive_arr)

Array of consecutive Integer:  [0 1 2 3 4 5 6 7 8 9]


In [3]:
#e.Crete 2D array
twod_array=np.array([[1,2,3,4],[5,6,7,8]])
print("2D array: ",twod_array)

2D array:  [[1 2 3 4]
 [5 6 7 8]]


In [5]:
# f. Sort the array
unsortarray=np.array([3,5,3,7,5,8,2,4,6,3,6,77,89,223,44,5,6,0,11,2])
sortarray=np.sort(unsortarray)
print("Originl array: ",unsortarray)
print("Sorted Array : ",sortarray)

Originl array:  [  3   5   3   7   5   8   2   4   6   3   6  77  89 223  44   5   6   0
  11   2]
Sorted Array :  [  0   2   2   3   3   3   4   5   5   5   6   6   6   7   8  11  44  77
  89 223]


In [9]:
# g. Find shape, size, dimension
arra3=np.array([[1,2,3,4,5,6,2],[3,2,1,4,5,6,7]])
print("shape: ",arra3.shape)
print("size: ",arra3.size)
print("Dimension: ",arra3.ndim) 

shape:  (2, 7)
size:  14
Dimension:  2


In [10]:
# h. Reshape the array
reshape_array=np.reshape(consecutive_arr,(2,5))
print("Reshape array : ",reshape_array) 
                         

Reshape array :  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# i. Increase dimension
expanded_arr=np.expand_dims(arr1,axis=0)
print("Expanded Array shape: ",expanded_arr.shape)

Expanded Array shape:  (1, 3)


In [12]:
# j. Indexing and slicing
print("Arrya Idex: ",arr1[0])
print("Array slicing: ",arr1[1:])

Arrya Idex:  1
Array slicing:  [2 3]


In [13]:
# k. Create an array from existing data
copied_arr =np.copy(arr1)
print("Copied Array:",copied_arr)


Copied Array: [1 2 3]


In [14]:
# l. Reshape existing array
reshape_existing=np.reshape(arr1,(3,1))
print("Reshape existig array : ",reshape_existing)

Reshape existig array :  [[1]
 [2]
 [3]]


In [15]:
# m. Print the array in vertical and horizontal stack
vstacked=np.vstack((arr1,arr2))
hstacked=np.hstack((arr1,arr2))
print("Vertical stack: \n",vstacked)
print("Horizontal stack: \n",hstacked)

Vertical stack: 
 [[1 2 3]
 [4 5 6]]
Horizontal stack: 
 [1 2 3 4 5 6]


In [16]:
# n. Split the array
split_arr=np.array_split(concatenated_arr,2)
print("Split Arrays: ",split_arr)

Split Arrays:  [array([1, 2, 3]), array([4, 5, 6])]


In [17]:
# o. Basic array operations
sum_arr=arr1+arr2
diff_arr=arr1-arr2
prod_arr=arr1*arr2
print("Sum : ",sum_arr)
print("Difference : ",diff_arr)
print("Product: ",prod_arr)

Sum :  [5 7 9]
Difference :  [-3 -3 -3]
Product:  [ 4 10 18]


In [19]:
# p. Summary of the array
print("Mean: ",np.mean(arr1))
print("Standard Deviation: ",np.std(arr1))

Mean:  2.0
Standard Deviation:  0.816496580927726


In [22]:
# q. Multiply elements in array
multiplied_arr=arr1*200
print("Mulitipilied Array: ",multiplied_arr)

Mulitipilied Array:  [200 400 600]


In [23]:
# r. Find max and min
print("Min : ",np.min(arr1))
print("Max : ",np.max(arr1))

Min :  1
Max :  3


In [24]:
# s. Transpose of array
transpose_two_d=np.transpose(twod_array)
print("Transposed 2D array: \n",transpose_two_d)

Transposed 2D array: 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
